import type { CollectionConfig } from 'payload'
import { adminOnly, hiddenUnlessAdmin } from './access'

// One row per project: the rendered reel + carousel cards (URLs in R2),
// written by `npm run social:generate -- <slug>` (scripts/social/generate.ts).
// Kept out of the Project document on purpose — the CLI writes these while
// the project may be open in /cms, and a later Save of that stale form would
// otherwise overwrite them. Payload-only (not mirrored to Supabase), like
// Leads and Analytics.
export const SocialAssets: CollectionConfig = {
  slug: 'social-assets',
  admin: {
    group: 'Marketing',
    useAsTitle: 'id',
    defaultColumns: ['project', 'reelUrl', 'generatedAt'],
    hidden: hiddenUnlessAdmin,
    description: 'Generated by the social renderer CLI. Preview and post from the project\'s Social tab.',
  },
  access: { read: adminOnly, create: adminOnly, update: adminOnly, delete: adminOnly },
  fields: [
    { name: 'project', type: 'relationship', relationTo: 'projects', required: true, unique: true, index: true },
    { name: 'reelUrl', type: 'text', label: 'Reel (MP4)' },
    { name: 'reelPosterUrl', type: 'text', label: 'Reel poster' },
    { name: 'reelDurationSec', type: 'number', label: 'Reel length (s)' },
    { name: 'cards', type: 'array', label: 'Carousel cards (4:5)', fields: [{ name: 'url', type: 'text', required: true }] },
    { name: 'generatedAt', type: 'date' },
    { name: 'notes', type: 'text', admin: { description: 'What the generator used (photo count, depth on/off, plan scenes).' } },
  ],
}
