/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    developers: Developer;
    projects: Project;
    lands: Land;
    'construction-companies': ConstructionCompany;
    'marketing-companies': MarketingCompany;
    'sales-companies': SalesCompany;
    architects: Architect;
    'interior-designers': InteriorDesigner;
    neighborhoods: Neighborhood;
    'hero-slides': HeroSlide;
    'saved-listings': SavedListing;
    leads: Lead;
    analytics: Analytics;
    payments: Payment;
    'placement-pricing': PlacementPricing;
    'team-members': TeamMember;
    articles: Article;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    developers: {
      projects: 'projects';
      team_members: 'team-members';
    };
    'construction-companies': {
      team_members: 'team-members';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    developers: DevelopersSelect<false> | DevelopersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    lands: LandsSelect<false> | LandsSelect<true>;
    'construction-companies': ConstructionCompaniesSelect<false> | ConstructionCompaniesSelect<true>;
    'marketing-companies': MarketingCompaniesSelect<false> | MarketingCompaniesSelect<true>;
    'sales-companies': SalesCompaniesSelect<false> | SalesCompaniesSelect<true>;
    architects: ArchitectsSelect<false> | ArchitectsSelect<true>;
    'interior-designers': InteriorDesignersSelect<false> | InteriorDesignersSelect<true>;
    neighborhoods: NeighborhoodsSelect<false> | NeighborhoodsSelect<true>;
    'hero-slides': HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    'saved-listings': SavedListingsSelect<false> | SavedListingsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    analytics: AnalyticsSelect<false> | AnalyticsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'placement-pricing': PlacementPricingSelect<false> | PlacementPricingSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  full_name: string;
  phone?: string | null;
  role: 'buyer' | 'developer' | 'construction_company' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developers".
 */
export interface Developer {
  id: number;
  slug: string;
  name: string;
  /**
   * Logo image URL
   */
  logo?: string | null;
  description?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  website?: string | null;
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
    whatsapp?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
  };
  /**
   * The developer-role account that manages this company profile.
   */
  user?: (number | null) | User;
  projects?: {
    docs?: (number | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  team_members?: {
    docs?: (number | TeamMember)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Gates the "Developer approval" workflow — new self-registered developers start pending.
   */
  verification_status?: ('pending' | 'approved' | 'rejected' | 'changes_requested') | null;
  seo?: {
    seoTitle?: string | null;
    seoDescription?: string | null;
    /**
     * Image URL
     */
    ogImage?: string | null;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  slug: string;
  name: string;
  developer: number | Developer;
  architect?: (number | null) | Architect;
  marketing_company?: (number | null) | MarketingCompany;
  sales_company?: (number | null) | SalesCompany;
  interior_designer?: (number | null) | InteriorDesigner;
  location?: string | null;
  district?:
    | (
        | 'Colombo'
        | 'Gampaha'
        | 'Kalutara'
        | 'Kandy'
        | 'Matale'
        | 'Nuwara Eliya'
        | 'Galle'
        | 'Matara'
        | 'Hambantota'
        | 'Jaffna'
        | 'Kilinochchi'
        | 'Mannar'
        | 'Vavuniya'
        | 'Mullaitivu'
        | 'Batticaloa'
        | 'Ampara'
        | 'Trincomalee'
        | 'Kurunegala'
        | 'Puttalam'
        | 'Anuradhapura'
        | 'Polonnaruwa'
        | 'Badulla'
        | 'Monaragala'
        | 'Ratnapura'
        | 'Kegalle'
      )
    | null;
  /**
   * Custom value, used when District above doesn't have the right option.
   */
  district_other?: string | null;
  city?: string | null;
  province?:
    | (
        | 'Western'
        | 'Central'
        | 'Southern'
        | 'Northern'
        | 'Eastern'
        | 'North Western'
        | 'North Central'
        | 'Uva'
        | 'Sabaragamuwa'
      )
    | null;
  /**
   * Custom value, used when Province above doesn't have the right option.
   */
  province_other?: string | null;
  neighborhood?: (number | null) | Neighborhood;
  /**
   * Custom value, used when the neighborhood above isn't in the system yet.
   */
  neighborhood_other?: string | null;
  neighborhoodSlug?: string | null;
  road?: string | null;
  area?: string | null;
  electricity?: ('Available' | '3-Phase Available' | 'Metered' | 'Not Available' | 'Solar') | null;
  /**
   * Custom value, used when Electricity above doesn't have the right option.
   */
  electricity_other?: string | null;
  tapWater?: ('Available' | 'Metered' | 'Not Available' | 'Well Water') | null;
  /**
   * Custom value, used when Tap Water above doesn't have the right option.
   */
  tapWater_other?: string | null;
  type?: ('Apartments' | 'Condominium' | 'Villas' | 'House' | 'Townhouse' | 'Serviced Apartment' | 'Mixed-Use') | null;
  /**
   * Custom value, used when Type above doesn't have the right option.
   */
  type_other?: string | null;
  status?:
    | ('Now Selling' | 'Coming Soon' | 'Under Construction' | 'Launching Soon' | 'Nearly Sold Out' | 'Nearly Complete')
    | null;
  featured?: boolean | null;
  isMoveInNow?: boolean | null;
  /**
   * Auto-set true once every item on the Verification tab is checked off.
   */
  isVerified?: boolean | null;
  /**
   * Free-text credits for co-developers that don’t have a Developer record here.
   */
  coDevelopers?:
    | {
        name: string;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Other developer companies credited on this project (secondary — the primary developer above owns edit access).
   */
  additional_developers?: (number | Developer)[] | null;
  /**
   * Construction companies / builders credited on this project.
   */
  additional_builders?: (number | ConstructionCompany)[] | null;
  launchDate?: string | null;
  completionYear?: number | null;
  constructionStatus?:
    | (
        | 'Not Started'
        | 'Foundation'
        | 'Under Construction'
        | 'Structure Complete'
        | 'Finishing'
        | 'Completed'
        | 'Ready to Move In'
      )
    | null;
  /**
   * Custom value, used when Construction Status above doesn't have the right option.
   */
  constructionStatus_other?: string | null;
  constructionStarted?: string | null;
  statusHistory?:
    | {
        date?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  completionDateHistory?:
    | {
        date?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  availabilityHistory?:
    | {
        date?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  startingPriceLkr?: number | null;
  priceRange?: string | null;
  bedrooms?: string | null;
  bathrooms?: string | null;
  floorAreaRange?: string | null;
  units?: number | null;
  floors?: number | null;
  carparkLevels?: number | null;
  averageUnitPriceLkr?: number | null;
  averageFloorAreaSqFt?: number | null;
  parking?: string | null;
  security?: string | null;
  ownership?: ('Freehold' | 'Leasehold' | 'Condominium') | null;
  /**
   * Custom value, used when Ownership above doesn't have the right option.
   */
  ownership_other?: string | null;
  ceilingInfo?: string | null;
  paymentPlan?: string | null;
  paymentPlanItems?: string[] | null;
  availablePlanPrices?: string | null;
  pricingComingSoon?: string | null;
  averagePricePerSqft?: string | null;
  monthlyMaintenancePerSqft?: string | null;
  propertyTax?: string | null;
  parkingCost?: string | null;
  storageCost?: string | null;
  coopFeeRealtors?: string | null;
  depositPaymentStructure?: string | null;
  incentives?: string[] | null;
  pricingHistory?:
    | {
        date?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  summary?: string | null;
  description?: string | null;
  /**
   * Image URL
   */
  heroImage?: string | null;
  gallery?:
    | {
        label?: string | null;
        /**
         * Image URL
         */
        image: string;
        id?: string | null;
      }[]
    | null;
  brochureUrl?: string | null;
  videos?:
    | {
        label?: string | null;
        embedUrl?: string | null;
        thumbnail?: string | null;
        id?: string | null;
      }[]
    | null;
  virtualTours?:
    | {
        label?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  interactiveMapUrl?: string | null;
  /**
   * Which detail chips show in the listing icon stats on mobile. Maximum 10.
   */
  mobileVisibleStats?:
    | (
        | 'Listing status'
        | 'Building status'
        | 'Price CAD'
        | 'Price range'
        | 'Address'
        | 'Total units'
        | 'Total Units'
        | 'Floor plans'
        | 'Stories'
        | 'Floors'
        | 'Property type'
        | 'Beds'
        | 'Baths'
        | 'SqFt'
        | 'Move in'
        | 'Units sold'
        | 'Units available'
        | 'Road'
        | 'Area'
        | 'Electricity'
        | 'Tap water'
        | 'Per SqFt (Avg)'
        | 'Incentives'
        | 'Parking'
        | 'Carpark levels'
        | 'Avg unit price'
        | 'Avg floor area'
        | 'Ownership'
        | 'Ceilings'
        | 'Neighborhood'
        | 'Security'
        | 'District'
        | 'Sales started'
      )[]
    | null;
  /**
   * Which detail chips show in the listing icon stats on desktop. Maximum 10.
   */
  desktopVisibleStats?:
    | (
        | 'Listing status'
        | 'Building status'
        | 'Price CAD'
        | 'Price range'
        | 'Address'
        | 'Total units'
        | 'Total Units'
        | 'Floor plans'
        | 'Stories'
        | 'Floors'
        | 'Property type'
        | 'Beds'
        | 'Baths'
        | 'SqFt'
        | 'Move in'
        | 'Units sold'
        | 'Units available'
        | 'Road'
        | 'Area'
        | 'Electricity'
        | 'Tap water'
        | 'Per SqFt (Avg)'
        | 'Incentives'
        | 'Parking'
        | 'Carpark levels'
        | 'Avg unit price'
        | 'Avg floor area'
        | 'Ownership'
        | 'Ceilings'
        | 'Neighborhood'
        | 'Security'
        | 'District'
        | 'Sales started'
      )[]
    | null;
  amenities?:
    | {
        name:
          | 'Pool'
          | 'Gym'
          | 'Rooftop'
          | 'Parking'
          | 'Security'
          | 'CCTV'
          | 'Garden'
          | "Children's Area"
          | 'Clubhouse'
          | 'EV Charging'
          | 'Concierge'
          | 'Padel Court'
          | 'Resident Lounge'
          | 'Private Elevator'
          | 'Utility Area'
          | 'Outdoor Kitchen'
          | 'Infinity Pool'
          | 'Games Room'
          | 'Sky Lounge'
          | 'Retail Mall'
          | 'Hotel'
          | 'Gated Community'
          | 'Beachfront'
          | 'Sea View';
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  unitFeatures?:
    | {
        key?: ('indoor' | 'outdoor') | null;
        /**
         * Custom value, used when Category above doesn't have the right option.
         */
        key_other?: string | null;
        label: string;
        items?:
          | {
              field?:
                | (
                    | 'Kitchen'
                    | 'Bathroom'
                    | 'Windows'
                    | 'Climate'
                    | 'Lighting'
                    | 'Security'
                    | 'Connectivity'
                    | 'Laundry'
                    | 'Storage'
                    | 'Appliances'
                    | 'Flooring'
                    | 'Balcony'
                    | 'Garden'
                    | 'Pool'
                    | 'Parking'
                    | 'Outdoor Kitchen'
                    | 'View'
                    | 'Landscaping'
                  )
                | null;
              /**
               * Custom value, used when Feature above doesn't have the right option.
               */
              field_other?: string | null;
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  factsGrid?:
    | {
        key: string;
        label: string;
        value: string;
        icon:
          | 'building-2'
          | 'wrench'
          | 'layout-grid'
          | 'footprints'
          | 'bed-double'
          | 'bath'
          | 'ruler'
          | 'parking-circle'
          | 'file-text'
          | 'hard-hat'
          | 'dollar-sign'
          | 'calendar'
          | 'shield'
          | 'warehouse'
          | 'paw-print';
        id?: string | null;
      }[]
    | null;
  includedUtilities?: string[] | null;
  paidUtilities?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  floorPlans?:
    | {
        planName: string;
        planType?: string | null;
        bedrooms: number;
        bathrooms: number;
        floorAreaSqFt: number;
        interiorSizeSqFt?: number | null;
        balconySizeSqFt?: number | null;
        basement?: string | null;
        garage?: string | null;
        parkingSpaces?: number | null;
        startingPriceLkr: number;
        /**
         * Image URL
         */
        image?: string | null;
        availability?: ('Available' | 'Limited' | 'Sold Out') | null;
        quickMoveIn?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Which detail chips show on the floor plan page. Maximum 10.
   */
  floorPlanVisibleStats?:
    | (
        | 'Listing status'
        | 'Building status'
        | 'Price CAD'
        | 'Price range'
        | 'Address'
        | 'Total units'
        | 'Total Units'
        | 'Floor plans'
        | 'Stories'
        | 'Floors'
        | 'Property type'
        | 'Beds'
        | 'Baths'
        | 'SqFt'
        | 'Move in'
        | 'Units sold'
        | 'Units available'
        | 'Road'
        | 'Area'
        | 'Electricity'
        | 'Tap water'
        | 'Per SqFt (Avg)'
        | 'Incentives'
        | 'Parking'
        | 'Carpark levels'
        | 'Avg unit price'
        | 'Avg floor area'
        | 'Ownership'
        | 'Ceilings'
        | 'Neighborhood'
        | 'Security'
        | 'District'
        | 'Sales started'
      )[]
    | null;
  hotDeal?: {
    enabled?: boolean | null;
    badge?: string | null;
    title?: string | null;
    description?: string | null;
  };
  nearby?:
    | {
        category: 'School' | 'Hospital' | 'Shopping' | 'Restaurant' | 'Transport' | 'Landmark';
        name: string;
        distanceKm?: number | null;
        id?: string | null;
      }[]
    | null;
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  contact?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  /**
   * Auto-calculated from how many key fields are filled in.
   */
  completeness_score?: number | null;
  /**
   * Auto-incremented from Analytics "view" events for this project.
   */
  view_count?: number | null;
  /**
   * Auto-incremented from Analytics "save" events (logged automatically when a Saved Listing is created).
   */
  save_count?: number | null;
  /**
   * Auto-incremented from Analytics "lead_submitted" events (logged automatically when a Lead is created).
   */
  lead_count?: number | null;
  /**
   * Paid featured placements — one row per page/window, added automatically when a featured_listing payment is confirmed.
   */
  placements?:
    | {
        page:
          | 'sitewide'
          | 'colombo'
          | 'colombo-luxury'
          | 'pre-construction'
          | 'branded-residences'
          | 'villas'
          | 'beachfront'
          | 'serviced-apartments'
          | 'port-city-colombo'
          | 'search'
          | 'land';
        start_date?: string | null;
        end_date?: string | null;
        source_payment?: (number | null) | Payment;
        id?: string | null;
      }[]
    | null;
  /**
   * Manually set by admin — added into final_score to rank this project higher.
   */
  paid_boost?: number | null;
  /**
   * Auto-calculated: completeness + engagement + recency + paid_boost.
   */
  final_score?: number | null;
  seo?: {
    seoTitle?: string | null;
    seoDescription?: string | null;
    /**
     * Image URL
     */
    ogImage?: string | null;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  verification_developer_verified?: boolean | null;
  verification_address_verified?: boolean | null;
  verification_price_verified?: boolean | null;
  verification_floor_plans_verified?: boolean | null;
  verification_completion_date_verified?: boolean | null;
  verification_ownership_verified?: boolean | null;
  verification_documents_verified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "architects".
 */
export interface Architect {
  id: number;
  slug: string;
  name: string;
  /**
   * Logo image URL
   */
  logo?: string | null;
  description?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  portfolio_link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-companies".
 */
export interface MarketingCompany {
  id: number;
  slug: string;
  name: string;
  /**
   * Logo image URL
   */
  logo?: string | null;
  description?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  services?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales-companies".
 */
export interface SalesCompany {
  id: number;
  slug: string;
  name: string;
  /**
   * Logo image URL
   */
  logo?: string | null;
  description?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  services?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interior-designers".
 */
export interface InteriorDesigner {
  id: number;
  slug: string;
  name: string;
  /**
   * Logo image URL
   */
  logo?: string | null;
  description?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  portfolio_link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "neighborhoods".
 */
export interface Neighborhood {
  id: number;
  slug: string;
  name: string;
  city?: string | null;
  province?: string | null;
  description?: string | null;
  /**
   * Image URL
   */
  heroImage?: string | null;
  seo?: {
    seoTitle?: string | null;
    seoDescription?: string | null;
    /**
     * Image URL
     */
    ogImage?: string | null;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "construction-companies".
 */
export interface ConstructionCompany {
  id: number;
  slug: string;
  name: string;
  /**
   * Logo image URL
   */
  logo?: string | null;
  description?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  services?: string[] | null;
  /**
   * The construction_company-role account that manages this profile.
   */
  user?: (number | null) | User;
  team_members?: {
    docs?: (number | TeamMember)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  company:
    | {
        relationTo: 'developers';
        value: number | Developer;
      }
    | {
        relationTo: 'construction-companies';
        value: number | ConstructionCompany;
      };
  user: number | User;
  role: 'owner' | 'sales' | 'marketing' | 'member';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  /**
   * The developer or construction company (builder) this payment is for.
   */
  payer:
    | {
        relationTo: 'developers';
        value: number | Developer;
      }
    | {
        relationTo: 'construction-companies';
        value: number | ConstructionCompany;
      };
  amount: number;
  currency: 'LKR' | 'USD';
  payment_type:
    | 'featured_listing'
    | 'featured_search'
    | 'hero_slide'
    | 'hero_image'
    | 'banner_ad'
    | 'top_of_category'
    | 'subscription'
    | 'lead_package';
  related_project?: (number | null) | Project;
  /**
   * For a featured_listing (or featured_search) payment: which page to feature the project on once confirmed.
   */
  featured_page?:
    | (
        | 'sitewide'
        | 'colombo'
        | 'colombo-luxury'
        | 'pre-construction'
        | 'branded-residences'
        | 'villas'
        | 'beachfront'
        | 'serviced-apartments'
        | 'port-city-colombo'
        | 'search'
        | 'land'
      )
    | null;
  status: 'pending' | 'completed' | 'failed' | 'refunded';
  payment_date?: string | null;
  /**
   * For time-limited placements, e.g. a featured-listing or hero-slide window.
   */
  expiry_date?: string | null;
  /**
   * Placeholder for a future payment provider (e.g. Stripe) reference id.
   */
  provider_reference?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lands".
 */
export interface Land {
  id: number;
  slug: string;
  title: string;
  sellerType: 'developer' | 'construction_company' | 'builder';
  /**
   * Used when sellerType is developer or construction_company.
   */
  seller?:
    | ({
        relationTo: 'developers';
        value: number | Developer;
      } | null)
    | ({
        relationTo: 'construction-companies';
        value: number | ConstructionCompany;
      } | null);
  /**
   * Always shown; the only identifier when sellerType is "builder".
   */
  sellerName: string;
  location?: string | null;
  district?: string | null;
  city?: string | null;
  province?: string | null;
  status: 'Available' | 'Reserved' | 'Sold';
  isFeatured?: boolean | null;
  landSizePerches: number;
  landSizeAcres?: number | null;
  priceLkr: number;
  pricePerPerchLkrMin?: number | null;
  pricePerPerchLkrMax?: number | null;
  /**
   * e.g. Residential, Commercial, Agricultural, Mixed
   */
  landUse: string;
  /**
   * e.g. Bare Land, Land with House, Paddy Land, Coconut Land
   */
  landType?: string | null;
  /**
   * e.g. Rectangular, Square, Irregular, L-Shaped
   */
  landShape?: string | null;
  roadAccess?: string | null;
  roadWidthFt?: number | null;
  electricity?: string | null;
  water?: string | null;
  /**
   * e.g. Freehold - Sinhala Deed, Freehold - Swarnabhoomi, Torrens Title
   */
  titleType?: string | null;
  surveyPlanStatus?: string | null;
  paymentPlanItems?: string[] | null;
  summary?: string | null;
  description?: string | null;
  /**
   * Image URL
   */
  heroImage?: string | null;
  gallery?:
    | {
        label?: string | null;
        /**
         * Image URL
         */
        image: string;
        id?: string | null;
      }[]
    | null;
  blockPlanImages?:
    | {
        label?: string | null;
        /**
         * Image URL
         */
        image: string;
        id?: string | null;
      }[]
    | null;
  roadMapImages?:
    | {
        label?: string | null;
        /**
         * Image URL
         */
        image: string;
        id?: string | null;
      }[]
    | null;
  videos?:
    | {
        label?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Marketing trust badges, e.g. "Easy Payment Plan"
   */
  badges?: string[] | null;
  /**
   * General parcel characteristics, e.g. "Wide Road", "Corner Plot"
   */
  facilities?: string[] | null;
  amenities?:
    | {
        name:
          | 'Pool'
          | 'Gym'
          | 'Rooftop'
          | 'Parking'
          | 'Security'
          | 'CCTV'
          | 'Garden'
          | "Children's Area"
          | 'Clubhouse'
          | 'EV Charging'
          | 'Concierge'
          | 'Padel Court'
          | 'Resident Lounge'
          | 'Private Elevator'
          | 'Utility Area'
          | 'Outdoor Kitchen'
          | 'Infinity Pool'
          | 'Games Room'
          | 'Sky Lounge'
          | 'Retail Mall'
          | 'Hotel'
          | 'Gated Community'
          | 'Beachfront'
          | 'Sea View';
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  unitFeatures?:
    | {
        key?: ('indoor' | 'outdoor') | null;
        /**
         * Custom value, used when Category above doesn't have the right option.
         */
        key_other?: string | null;
        label: string;
        items?:
          | {
              field?:
                | (
                    | 'Kitchen'
                    | 'Bathroom'
                    | 'Windows'
                    | 'Climate'
                    | 'Lighting'
                    | 'Security'
                    | 'Connectivity'
                    | 'Laundry'
                    | 'Storage'
                    | 'Appliances'
                    | 'Flooring'
                    | 'Balcony'
                    | 'Garden'
                    | 'Pool'
                    | 'Parking'
                    | 'Outdoor Kitchen'
                    | 'View'
                    | 'Landscaping'
                  )
                | null;
              /**
               * Custom value, used when Feature above doesn't have the right option.
               */
              field_other?: string | null;
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Individual plots/lots within this land development — omit for a single unsubdivided parcel.
   */
  plots?:
    | {
        name: string;
        sizePerches: number;
        priceLkr: number;
        status: 'Available' | 'Reserved' | 'Sold';
        /**
         * Image URL
         */
        image?: string | null;
        id?: string | null;
      }[]
    | null;
  nearby?:
    | {
        category: 'School' | 'Hospital' | 'Shopping' | 'Restaurant' | 'Transport' | 'Landmark';
        name: string;
        distanceKm?: number | null;
        id?: string | null;
      }[]
    | null;
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  contact?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  seo?: {
    seoTitle?: string | null;
    seoDescription?: string | null;
    /**
     * Image URL
     */
    ogImage?: string | null;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides".
 */
export interface HeroSlide {
  id: number;
  /**
   * Image URL
   */
  image: string;
  link?: string | null;
  /**
   * e.g. homepage, colombo, luxury
   */
  page_target?: string | null;
  display_order?: number | null;
  advertiser?: (number | null) | Developer;
  start_date?: string | null;
  end_date?: string | null;
  is_paid_placement?: boolean | null;
  status?: ('pending' | 'active' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-listings".
 */
export interface SavedListing {
  id: number;
  user: number | User;
  project: number | Project;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  user?: (number | null) | User;
  project: number | Project;
  name: string;
  email: string;
  phone?: string | null;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics".
 */
export interface Analytics {
  id: number;
  project: number | Project;
  event_type: 'view' | 'save' | 'lead_submitted' | 'hero_click';
  timestamp?: string | null;
  user?: (number | null) | User;
  /**
   * Which page the event happened on, e.g. colombo, sitewide
   */
  source_page?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placement-pricing".
 */
export interface PlacementPricing {
  id: number;
  payment_type:
    | 'featured_listing'
    | 'featured_search'
    | 'hero_slide'
    | 'hero_image'
    | 'banner_ad'
    | 'top_of_category'
    | 'subscription'
    | 'lead_package';
  /**
   * For featured_listing/featured_search: which page this price applies to. Leave blank for a page-independent price.
   */
  featured_page?:
    | (
        | 'sitewide'
        | 'colombo'
        | 'colombo-luxury'
        | 'pre-construction'
        | 'branded-residences'
        | 'villas'
        | 'beachfront'
        | 'serviced-apartments'
        | 'port-city-colombo'
        | 'search'
        | 'land'
      )
    | null;
  /**
   * e.g. "Professional", "50 Leads" — lets subscription/lead_package have multiple price points.
   */
  tier_name?: string | null;
  price: number;
  currency: 'LKR' | 'USD';
  /**
   * How many days this price covers, e.g. 30 for a monthly placement window.
   */
  duration_days?: number | null;
  description?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  slug: string;
  title: string;
  excerpt: string;
  category: 'Buying Guide' | 'Market Insight' | 'Finance';
  /**
   * e.g. "5 min read"
   */
  readTime?: string | null;
  /**
   * Image URL
   */
  image?: string | null;
  author?: string | null;
  publishedDate?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'developers';
        value: number | Developer;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'lands';
        value: number | Land;
      } | null)
    | ({
        relationTo: 'construction-companies';
        value: number | ConstructionCompany;
      } | null)
    | ({
        relationTo: 'marketing-companies';
        value: number | MarketingCompany;
      } | null)
    | ({
        relationTo: 'sales-companies';
        value: number | SalesCompany;
      } | null)
    | ({
        relationTo: 'architects';
        value: number | Architect;
      } | null)
    | ({
        relationTo: 'interior-designers';
        value: number | InteriorDesigner;
      } | null)
    | ({
        relationTo: 'neighborhoods';
        value: number | Neighborhood;
      } | null)
    | ({
        relationTo: 'hero-slides';
        value: number | HeroSlide;
      } | null)
    | ({
        relationTo: 'saved-listings';
        value: number | SavedListing;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'analytics';
        value: number | Analytics;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'placement-pricing';
        value: number | PlacementPricing;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  full_name?: T;
  phone?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developers_select".
 */
export interface DevelopersSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  logo?: T;
  description?: T;
  contact_email?: T;
  contact_phone?: T;
  website?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        twitter?: T;
        whatsapp?: T;
        youtube?: T;
        tiktok?: T;
      };
  user?: T;
  projects?: T;
  team_members?: T;
  verification_status?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  developer?: T;
  architect?: T;
  marketing_company?: T;
  sales_company?: T;
  interior_designer?: T;
  location?: T;
  district?: T;
  district_other?: T;
  city?: T;
  province?: T;
  province_other?: T;
  neighborhood?: T;
  neighborhood_other?: T;
  neighborhoodSlug?: T;
  road?: T;
  area?: T;
  electricity?: T;
  electricity_other?: T;
  tapWater?: T;
  tapWater_other?: T;
  type?: T;
  type_other?: T;
  status?: T;
  featured?: T;
  isMoveInNow?: T;
  isVerified?: T;
  coDevelopers?:
    | T
    | {
        name?: T;
        href?: T;
        id?: T;
      };
  additional_developers?: T;
  additional_builders?: T;
  launchDate?: T;
  completionYear?: T;
  constructionStatus?: T;
  constructionStatus_other?: T;
  constructionStarted?: T;
  statusHistory?:
    | T
    | {
        date?: T;
        note?: T;
        id?: T;
      };
  completionDateHistory?:
    | T
    | {
        date?: T;
        note?: T;
        id?: T;
      };
  availabilityHistory?:
    | T
    | {
        date?: T;
        note?: T;
        id?: T;
      };
  startingPriceLkr?: T;
  priceRange?: T;
  bedrooms?: T;
  bathrooms?: T;
  floorAreaRange?: T;
  units?: T;
  floors?: T;
  carparkLevels?: T;
  averageUnitPriceLkr?: T;
  averageFloorAreaSqFt?: T;
  parking?: T;
  security?: T;
  ownership?: T;
  ownership_other?: T;
  ceilingInfo?: T;
  paymentPlan?: T;
  paymentPlanItems?: T;
  availablePlanPrices?: T;
  pricingComingSoon?: T;
  averagePricePerSqft?: T;
  monthlyMaintenancePerSqft?: T;
  propertyTax?: T;
  parkingCost?: T;
  storageCost?: T;
  coopFeeRealtors?: T;
  depositPaymentStructure?: T;
  incentives?: T;
  pricingHistory?:
    | T
    | {
        date?: T;
        note?: T;
        id?: T;
      };
  summary?: T;
  description?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        label?: T;
        image?: T;
        id?: T;
      };
  brochureUrl?: T;
  videos?:
    | T
    | {
        label?: T;
        embedUrl?: T;
        thumbnail?: T;
        id?: T;
      };
  virtualTours?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  interactiveMapUrl?: T;
  mobileVisibleStats?: T;
  desktopVisibleStats?: T;
  amenities?:
    | T
    | {
        name?: T;
        icon?: T;
        id?: T;
      };
  unitFeatures?:
    | T
    | {
        key?: T;
        key_other?: T;
        label?: T;
        items?:
          | T
          | {
              field?: T;
              field_other?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  factsGrid?:
    | T
    | {
        key?: T;
        label?: T;
        value?: T;
        icon?: T;
        id?: T;
      };
  includedUtilities?: T;
  paidUtilities?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  floorPlans?:
    | T
    | {
        planName?: T;
        planType?: T;
        bedrooms?: T;
        bathrooms?: T;
        floorAreaSqFt?: T;
        interiorSizeSqFt?: T;
        balconySizeSqFt?: T;
        basement?: T;
        garage?: T;
        parkingSpaces?: T;
        startingPriceLkr?: T;
        image?: T;
        availability?: T;
        quickMoveIn?: T;
        id?: T;
      };
  floorPlanVisibleStats?: T;
  hotDeal?:
    | T
    | {
        enabled?: T;
        badge?: T;
        title?: T;
        description?: T;
      };
  nearby?:
    | T
    | {
        category?: T;
        name?: T;
        distanceKm?: T;
        id?: T;
      };
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  contact?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  completeness_score?: T;
  view_count?: T;
  save_count?: T;
  lead_count?: T;
  placements?:
    | T
    | {
        page?: T;
        start_date?: T;
        end_date?: T;
        source_payment?: T;
        id?: T;
      };
  paid_boost?: T;
  final_score?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  verification_developer_verified?: T;
  verification_address_verified?: T;
  verification_price_verified?: T;
  verification_floor_plans_verified?: T;
  verification_completion_date_verified?: T;
  verification_ownership_verified?: T;
  verification_documents_verified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lands_select".
 */
export interface LandsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  sellerType?: T;
  seller?: T;
  sellerName?: T;
  location?: T;
  district?: T;
  city?: T;
  province?: T;
  status?: T;
  isFeatured?: T;
  landSizePerches?: T;
  landSizeAcres?: T;
  priceLkr?: T;
  pricePerPerchLkrMin?: T;
  pricePerPerchLkrMax?: T;
  landUse?: T;
  landType?: T;
  landShape?: T;
  roadAccess?: T;
  roadWidthFt?: T;
  electricity?: T;
  water?: T;
  titleType?: T;
  surveyPlanStatus?: T;
  paymentPlanItems?: T;
  summary?: T;
  description?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        label?: T;
        image?: T;
        id?: T;
      };
  blockPlanImages?:
    | T
    | {
        label?: T;
        image?: T;
        id?: T;
      };
  roadMapImages?:
    | T
    | {
        label?: T;
        image?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  badges?: T;
  facilities?: T;
  amenities?:
    | T
    | {
        name?: T;
        icon?: T;
        id?: T;
      };
  unitFeatures?:
    | T
    | {
        key?: T;
        key_other?: T;
        label?: T;
        items?:
          | T
          | {
              field?: T;
              field_other?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  plots?:
    | T
    | {
        name?: T;
        sizePerches?: T;
        priceLkr?: T;
        status?: T;
        image?: T;
        id?: T;
      };
  nearby?:
    | T
    | {
        category?: T;
        name?: T;
        distanceKm?: T;
        id?: T;
      };
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  contact?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "construction-companies_select".
 */
export interface ConstructionCompaniesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  logo?: T;
  description?: T;
  contact_email?: T;
  contact_phone?: T;
  services?: T;
  user?: T;
  team_members?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-companies_select".
 */
export interface MarketingCompaniesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  logo?: T;
  description?: T;
  contact_email?: T;
  contact_phone?: T;
  services?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales-companies_select".
 */
export interface SalesCompaniesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  logo?: T;
  description?: T;
  contact_email?: T;
  contact_phone?: T;
  services?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "architects_select".
 */
export interface ArchitectsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  logo?: T;
  description?: T;
  contact_email?: T;
  contact_phone?: T;
  portfolio_link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interior-designers_select".
 */
export interface InteriorDesignersSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  logo?: T;
  description?: T;
  contact_email?: T;
  contact_phone?: T;
  portfolio_link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "neighborhoods_select".
 */
export interface NeighborhoodsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  city?: T;
  province?: T;
  description?: T;
  heroImage?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  image?: T;
  link?: T;
  page_target?: T;
  display_order?: T;
  advertiser?: T;
  start_date?: T;
  end_date?: T;
  is_paid_placement?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-listings_select".
 */
export interface SavedListingsSelect<T extends boolean = true> {
  user?: T;
  project?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  user?: T;
  project?: T;
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics_select".
 */
export interface AnalyticsSelect<T extends boolean = true> {
  project?: T;
  event_type?: T;
  timestamp?: T;
  user?: T;
  source_page?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  payer?: T;
  amount?: T;
  currency?: T;
  payment_type?: T;
  related_project?: T;
  featured_page?: T;
  status?: T;
  payment_date?: T;
  expiry_date?: T;
  provider_reference?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placement-pricing_select".
 */
export interface PlacementPricingSelect<T extends boolean = true> {
  payment_type?: T;
  featured_page?: T;
  tier_name?: T;
  price?: T;
  currency?: T;
  duration_days?: T;
  description?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  company?: T;
  user?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  excerpt?: T;
  category?: T;
  readTime?: T;
  image?: T;
  author?: T;
  publishedDate?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
    whatsapp?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
  };
  seoDefaults?: {
    defaultTitle?: string | null;
    defaultDescription?: string | null;
    /**
     * Image URL
     */
    defaultOgImage?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  contactEmail?: T;
  contactPhone?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        twitter?: T;
        whatsapp?: T;
        youtube?: T;
        tiktok?: T;
      };
  seoDefaults?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
        defaultOgImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}